### ISSUE TITLE
unsupported operand type(s)

### ISSUE THREAD

**Issue by niklasmeyer** [pklaus/brother_ql#9]
Hey,
while creating the .bin-file I always get this message. It still work's but wanted to let you know that this occurs:

    WARNING:brother_ql.brother_ql_create:Need to resize the image...
    Traceback (most recent call last):
      File "/usr/local/bin/brother_ql_print", line 11, in <module>
        load_entry_point('brother-ql==0.6.dev0', 'console_scripts', 'brother_ql_print')()
      File "/usr/local/lib/python2.7/dist-packages/brother_ql/brother_ql_print.py", line 85, in main
        result = interpret_response(data)
      File "/usr/local/lib/python2.7/dist-packages/brother_ql/reader.py", line 157, in interpret_response
        if error_info_1 & (1 << error_bit):
    TypeError: unsupported operand type(s) for &: 'str' and 'int'

Thanks a lot for the library!

Cheers

**Comment by pklaus** [comment]
The very first line in your console output is from the brother_ql_create tool. It's letting you know that it has to resize your picture, because you don't provide it with the ideal pixel dimensions right away. If you can, try to stick to the pixel dimensions that `brother_ql_info list-label-sizes` tells you.

The following lines are from the tool brother_ql_print. Let me quote the [print section](https://github.com/pklaus/brother_ql#print) of the README:

> [...] tool `brother_ql_print` (**_Py3 only_**) [...]

It's just not Python 2 compatible. (Sending the data should work, but interpreting the response fails.)
I'm surprised how many out there are still using Python 2. :) I'm currently not planning to make the tool Python 2 compatible but if there will be more issues coming in like this, I might consider porting it back.

Thanks again for the report and let me know if you can imagine any way to improve the library.
